// <auto-generated />
using System;
using EmailScheduler.src.Modules.EmailScheduler.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailScheduler.Migrations
{
    [DbContext(typeof(EmailSchedulerDbContext))]
    [Migration("20260628120722_EmailSchedulerMigration003")]
    partial class EmailSchedulerMigration003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailScheduler.src.Modules.EmailScheduler.Domain.EmailSchedulerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SmtpClientSettingsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TriggerDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SmtpClientSettingsId");

                    b.ToTable("EmailSchedulers");
                });

            modelBuilder.Entity("EmailScheduler.src.Modules.EmailScheduler.Domain.SmtpClientSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmtpClientSettingsSet");
                });

            modelBuilder.Entity("EmailScheduler.src.Modules.EmailScheduler.Domain.EmailSchedulerEntity", b =>
                {
                    b.HasOne("EmailScheduler.src.Modules.EmailScheduler.Domain.SmtpClientSettings", "SmtpClientSettings")
                        .WithMany("EmailSchedulers")
                        .HasForeignKey("SmtpClientSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmtpClientSettings");
                });

            modelBuilder.Entity("EmailScheduler.src.Modules.EmailScheduler.Domain.SmtpClientSettings", b =>
                {
                    b.Navigation("EmailSchedulers");
                });
#pragma warning restore 612, 618
        }
    }
}
